/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_Principal;

import Ayuda.ayuda;
import Clases1.fondo_imagen;
import Mantenimiento.mantenimiento;
import Reportes.reportes;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import mensajes.Mensaje_del_Dia;
import mensajes.Mensaje_Personal;

/**
 *
 * @author Administrador
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
//Atributos    
//Inicializo los valores x,y     
    int x = 0;
    int y = 0;

//Los paso como parametro de medidas para la imagen de fondo
    fondo_imagen p = new fondo_imagen(x, y, "/Imagenes/diseño lugo3.png");

//JInternal Frames
    Registros reg;
    Reportes.reportes rep;
    Mantenimiento.mantenimiento man;
    Ayuda.ayuda ayuda;

    public Menu() {
        initComponents();
//        setResizable(fal);//No se podra maximizar
        setLocationRelativeTo(null);//Centrar

        //Elimina el color de fondo del jPanel 
        //Es decir se vuelve Transparente
        jPanel1.setOpaque(false);
        jPanel2.setOpaque(false);
        //  panel_izq.setOpaque(false);
        jplescritorio2.setOpaque(false);

        //Se obtiene las medidas del jframe por lo que los valores de x,y 
        //Se actulizan
        x = this.getWidth();
        y = this.getHeight();

       //Se recrea el objeto para que pinte el frame con los nuevos
        //Valores de x,y
        //Se hace de esto debido a que a partir de este constructor los valores del 
        //jframe cambian.
        p = new fondo_imagen(x, y, "/Imagenes/diseño lugo3.png");
        //Se agrega el nuevo panel al jframe
        this.add(p);
        //Se empaqueta para que este se quede estatico sin modificar la posiciones de los
        //demas paneles.
        this.pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jplescritorio2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        btnMensajes = new javax.swing.JMenu();
        btndejar_mensaje = new javax.swing.JMenuItem();
        btn_Mensaje_Personal = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xorox 1.0.0");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jplescritorio2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jplescritorio2Layout = new javax.swing.GroupLayout(jplescritorio2);
        jplescritorio2.setLayout(jplescritorio2Layout);
        jplescritorio2Layout.setHorizontalGroup(
            jplescritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        jplescritorio2Layout.setVerticalGroup(
            jplescritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jplescritorio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jplescritorio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hombre-de-cerca-la-silueta-con-corbata.png"))); // NOI18N
        jMenu1.setText("Administracion");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/documentation.png"))); // NOI18N
        jMenuItem1.setText("Registros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diagram.png"))); // NOI18N
        jMenuItem2.setText("Reportes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DataBase-base-de-datos_A_1.png"))); // NOI18N
        jMenuItem3.setText("Mantenimiento");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        btnMensajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mensajeria.png"))); // NOI18N
        btnMensajes.setText("Mensajes");

        btndejar_mensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Email-send-icon.png"))); // NOI18N
        btndejar_mensaje.setText("Mensaje del Dia");
        btndejar_mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndejar_mensajeActionPerformed(evt);
            }
        });
        btnMensajes.add(btndejar_mensaje);

        btn_Mensaje_Personal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chat.png"))); // NOI18N
        btn_Mensaje_Personal.setText("Dejar Mensaje");
        btn_Mensaje_Personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Mensaje_PersonalActionPerformed(evt);
            }
        });
        btnMensajes.add(btn_Mensaje_Personal);

        jMenu1.add(btnMensajes);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda.png"))); // NOI18N
        jMenu3.setText("Ayuda");

        jMenuItem5.setText("Acerca de ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jMenu4.setText("Salir");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        if ((reg instanceof Registros)) {
            reg.dispose();
            reg = null;
        }
        if ((rep instanceof Reportes.reportes)) {
            rep.dispose();
            rep = null;
        }
        if ((man instanceof Mantenimiento.mantenimiento)) {
            man.dispose();
            man = null;
        }

        if ((ayuda instanceof Ayuda.ayuda)) {
            ayuda.dispose();
            ayuda = null;
        }

        if (!(ayuda instanceof Ayuda.ayuda)) {
            ayuda = new ayuda();
            CenterJInternalFrame(ayuda);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if ((reg instanceof Registros)) {
            reg.dispose();
            reg = null;
        }
        if ((rep instanceof Reportes.reportes)) {
            rep.dispose();
            rep = null;
        }
        if ((man instanceof Mantenimiento.mantenimiento)) {
            man.dispose();
            man = null;
        }

        if ((ayuda instanceof Ayuda.ayuda)) {
            ayuda.dispose();
            ayuda = null;
        }

        if (!(reg instanceof Registros)) {
            reg = new Registros();
            CenterJInternalFrame(reg);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if ((reg instanceof Registros)) {
            reg.dispose();
            reg = null;
        }
        if ((rep instanceof Reportes.reportes)) {
            rep.dispose();
            rep = null;
        }
        if ((man instanceof Mantenimiento.mantenimiento)) {
            man.dispose();
            man = null;
        }

        if ((ayuda instanceof Ayuda.ayuda)) {
            ayuda.dispose();
            ayuda = null;
        }

        if (!(rep instanceof reportes)) {
            rep = new reportes();
            CenterJInternalFrame(rep);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if ((reg instanceof Registros)) {
            reg.dispose();
            reg = null;
        }
        if ((rep instanceof Reportes.reportes)) {
            rep.dispose();
            rep = null;
        }
        if ((man instanceof Mantenimiento.mantenimiento)) {
            man.dispose();
            man = null;
        }

        if ((ayuda instanceof Ayuda.ayuda)) {
            ayuda.dispose();
            ayuda = null;
        }

        if (!(man instanceof Mantenimiento.mantenimiento)) {
            man = new mantenimiento();
            CenterJInternalFrame(man);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void btndejar_mensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndejar_mensajeActionPerformed
        // TODO add your handling code here:
        Mensaje_del_Dia a1=new Mensaje_del_Dia();
        CenterFrame(a1);
    }//GEN-LAST:event_btndejar_mensajeActionPerformed

    private void btn_Mensaje_PersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Mensaje_PersonalActionPerformed
        // TODO add your handling code here:
        Mensaje_Personal b1=new Mensaje_Personal();
        b1.setVisible(true);
    }//GEN-LAST:event_btn_Mensaje_PersonalActionPerformed

    public void CenterJInternalFrame(JInternalFrame internalframe) {

        int x = (jplescritorio2.getWidth() / 2) - internalframe.getWidth() / 2;
        int y = (jplescritorio2.getHeight() / 2) - internalframe.getHeight() / 2;
        if (internalframe.isShowing()) {
            internalframe.setLocation(x, y);
        } else {
            jplescritorio2.add(internalframe);
            internalframe.setLocation(x, y);
            internalframe.show();
        }
    }
    
    public void CenterFrame(JFrame frame) {

        int x = (jplescritorio2.getWidth() / 2) - frame.getWidth() / 2;
        int y = (jplescritorio2.getHeight() / 2) - frame.getHeight() / 2;
        if (frame.isShowing()) {
            frame.setLocation(x, y);
        } else {
            frame.setLocation(x, y);
            frame.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnMensajes;
    private javax.swing.JMenuItem btn_Mensaje_Personal;
    private javax.swing.JMenuItem btndejar_mensaje;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jplescritorio2;
    // End of variables declaration//GEN-END:variables
}
