/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_Principal;

import Clases1.fondo_imagen;
import Registros.Reg_Aulas;
import Registros.Reg_Carreras;
import Registros.Reg_Ciclo_Escolar;
import Registros.Reg_usuarios;
import Registros.Reg_Equipos;
import Registros.Reg_Horarios;
import Registros.Reg_Maestros;
import Registros.Reg_Materias;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class Registros extends javax.swing.JInternalFrame {

       int x=0;
       int y=0;

//Los paso como parametro de medidas para la imagen de fondo
fondo_imagen  p=new fondo_imagen(x,y,"/Imagenes/fondo16.png");  
    
//     Reg_usuarios regU;
     Reg_Equipos regE; 
     Reg_Horarios regH;
     Reg_Maestros regM;
     Reg_Aulas regA;
     Reg_Ciclo_Escolar regCC;
     Reg_Carreras RegCA;
     Reg_Materias reg_MA;
     Reg_usuarios regU;
     
    public Registros() {
        initComponents();
        Dimension t=Toolkit.getDefaultToolkit().getScreenSize();
         x=this.getWidth();
        y=this.getHeight();
        jPanel1.setOpaque(false);
       jplRegescritorio.setOpaque(false);
//       Se recrea el objeto para que pinte el frame con los nuevos
//       Valores de x,y
//       Se hace de esto debido a que a partir de este constructor los valores del 
//       jframe cambian.
        p=new fondo_imagen(x,y,"/Imagenes/fondo_Registros.png");
//        Se agrega el nuevo panel al jframe
        this.add(p);
//        Se empaqueta para que este se quede estatico sin modificar la posiciones de los
//        demas paneles.
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnusuarios = new javax.swing.JButton();
        btnmaestros = new javax.swing.JButton();
        btnhorario = new javax.swing.JButton();
        btnaula = new javax.swing.JButton();
        jplRegescritorio = new javax.swing.JPanel();
        btnCiclo_Escolar = new javax.swing.JButton();
        btnequipo = new javax.swing.JButton();
        btnCarreras = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estudiante.png"))); // NOI18N
        btnusuarios.setText("Alumnos");
        btnusuarios.setBorder(null);
        btnusuarios.setBorderPainted(false);
        btnusuarios.setContentAreaFilled(false);
        btnusuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnusuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnusuarios.setIconTextGap(1);
        btnusuarios.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnusuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 70, -1));

        btnmaestros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/businessman.png"))); // NOI18N
        btnmaestros.setText("Maestros");
        btnmaestros.setBorder(null);
        btnmaestros.setContentAreaFilled(false);
        btnmaestros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmaestros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmaestros.setIconTextGap(5);
        btnmaestros.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnmaestros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnmaestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmaestrosActionPerformed(evt);
            }
        });
        jPanel1.add(btnmaestros, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 60, 90));

        btnhorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendar.png"))); // NOI18N
        btnhorario.setText("Horario");
        btnhorario.setBorder(null);
        btnhorario.setBorderPainted(false);
        btnhorario.setContentAreaFilled(false);
        btnhorario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhorario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnhorario.setIconTextGap(5);
        btnhorario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnhorario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnhorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhorarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnhorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, 90));

        btnaula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/desk.png"))); // NOI18N
        btnaula.setText("Aulas ");
        btnaula.setBorder(null);
        btnaula.setBorderPainted(false);
        btnaula.setContentAreaFilled(false);
        btnaula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnaula.setIconTextGap(5);
        btnaula.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnaula.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnaula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaulaActionPerformed(evt);
            }
        });
        jPanel1.add(btnaula, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 70, 82));

        jplRegescritorio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jplRegescritorioLayout = new javax.swing.GroupLayout(jplRegescritorio);
        jplRegescritorio.setLayout(jplRegescritorioLayout);
        jplRegescritorioLayout.setHorizontalGroup(
            jplRegescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jplRegescritorioLayout.setVerticalGroup(
            jplRegescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        jPanel1.add(jplRegescritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        btnCiclo_Escolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/school.png"))); // NOI18N
        btnCiclo_Escolar.setText("Ciclo Escolar");
        btnCiclo_Escolar.setBorder(null);
        btnCiclo_Escolar.setBorderPainted(false);
        btnCiclo_Escolar.setContentAreaFilled(false);
        btnCiclo_Escolar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCiclo_Escolar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCiclo_Escolar.setIconTextGap(5);
        btnCiclo_Escolar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCiclo_Escolar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCiclo_Escolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiclo_EscolarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCiclo_Escolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 70, 90));

        btnequipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imac.png"))); // NOI18N
        btnequipo.setText("Equipo");
        btnequipo.setToolTipText("");
        btnequipo.setBorder(null);
        btnequipo.setBorderPainted(false);
        btnequipo.setContentAreaFilled(false);
        btnequipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnequipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnequipo.setIconTextGap(5);
        btnequipo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnequipo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnequipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequipoActionPerformed(evt);
            }
        });
        jPanel1.add(btnequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 70, 90));

        btnCarreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mortarboard.png"))); // NOI18N
        btnCarreras.setText("Carreras");
        btnCarreras.setBorder(null);
        btnCarreras.setBorderPainted(false);
        btnCarreras.setContentAreaFilled(false);
        btnCarreras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarreras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarreras.setIconTextGap(5);
        btnCarreras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCarreras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrerasActionPerformed(evt);
            }
        });
        jPanel1.add(btnCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, -1, 80));

        btnMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/notebook.png"))); // NOI18N
        btnMaterias.setText("Materias");
        btnMaterias.setBorder(null);
        btnMaterias.setBorderPainted(false);
        btnMaterias.setContentAreaFilled(false);
        btnMaterias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaterias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMaterias.setIconTextGap(5);
        btnMaterias.setInheritsPopupMenu(true);
        btnMaterias.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMaterias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriasActionPerformed(evt);
            }
        });
        jPanel1.add(btnMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuariosActionPerformed
        // TODO add your handling code here:
        if((regCC instanceof Reg_Ciclo_Escolar))
      { 
          regCC.dispose();
          regCC= null;
      }
        
          if((reg_MA instanceof Reg_Materias))
      { 
          reg_MA.dispose();
          reg_MA= null;
      }
     if((regA instanceof Reg_Aulas))
      { 
          regA.dispose();
          regA= null;
      }
     if((RegCA instanceof Reg_Carreras))
      { 
          RegCA.dispose();
          RegCA= null;
      }
        if((regH instanceof Reg_Horarios))
      { 
          regH.dispose();
          regH= null;
      }
        if((regE instanceof Reg_Equipos))
      { 
          regE.dispose();
          regE= null;
      }
    
            if((regM instanceof Reg_Maestros))
       {
          regM.dispose();
          regM=null;
       }
            
        if(!(regU instanceof Reg_usuarios))
      {  
               try
               {
                   regU  =new Reg_usuarios();
                   CenterJInternalFrame(regU);   
               }catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
               }
                  
                
      }                   
    }//GEN-LAST:event_btnusuariosActionPerformed

    private void btnequipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequipoActionPerformed
        // TODO add your handling code here:
        if((regCC instanceof Reg_Ciclo_Escolar))
      { 
          regCC.dispose();
          regCC= null;
      }
        
        if((reg_MA instanceof Reg_Materias))
      { 
          reg_MA.dispose();
          reg_MA= null;
      }
               
    if((regA instanceof Reg_Aulas))
      { 
          regA.dispose();
          regA= null;
      }
     if((RegCA instanceof Reg_Carreras))
      { 
          RegCA.dispose();
          RegCA= null;
      }
        if((regH instanceof Reg_Horarios))
      { 
          regH.dispose();
          regH= null;
      }
     
        if((regU instanceof Reg_usuarios))
      { 
         regU.dispose();
         regU= null;
      }
       
          if((regM instanceof Reg_Maestros))
       {
          regM.dispose();
          regM=null;
       }
        if(!(regE instanceof Reg_Equipos))
       {
    
            try {
                regE=new Reg_Equipos();
                CenterJInternalFrame(regE);
            } catch (Exception ex) {
                 JOptionPane.showMessageDialog(null, ex.getMessage());
            }
          
       }
        
      
    }//GEN-LAST:event_btnequipoActionPerformed

    private void btnmaestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmaestrosActionPerformed
        // TODO add your handling code here:
        if((regCC instanceof Reg_Ciclo_Escolar))
      { 
          regCC.dispose();
          regCC= null;
      }
         if((reg_MA instanceof Reg_Materias))
      { 
          reg_MA.dispose();
          reg_MA= null;
      }       
       if((regA instanceof Reg_Aulas))
      { 
          regA.dispose();
          regA= null;
      }
        if((RegCA instanceof Reg_Carreras))
      { 
          RegCA.dispose();
          RegCA= null;
      }
        if((regH instanceof Reg_Horarios))
      { 
          regH.dispose();
          regH= null;
      }
        if((regE instanceof Reg_Equipos))
      { 
          regE.dispose();
          regE= null;
      }
       if((regU instanceof Reg_usuarios))
      { 
         regU.dispose();
         regU= null;
      } 
        if(!(regM instanceof Reg_Maestros))
       {
           try
           {
           regM =new Reg_Maestros();
           CenterJInternalFrame(regM);
           }catch(Exception e)
           {
           JOptionPane.showMessageDialog(null, e.getMessage());
           }
          
       }
        
    }//GEN-LAST:event_btnmaestrosActionPerformed

    private void btnhorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhorarioActionPerformed
        // TODO add your handling code here:
        if((regCC instanceof Reg_Ciclo_Escolar))
      { 
          regCC.dispose();
          regCC= null;
      }       
         if((reg_MA instanceof Reg_Materias))
      { 
          reg_MA.dispose();
          reg_MA= null;
      }
         if((regA instanceof Reg_Aulas))
      { 
          regA.dispose();
          regA= null;
      }
        if((regE instanceof Reg_Equipos))
      { 
          regE.dispose();
          regE= null;
      }
        if((regU instanceof Reg_usuarios))
      { 
         regU.dispose();
         regU= null;
      }
       if((RegCA instanceof Reg_Carreras))
      { 
          RegCA.dispose();
          RegCA= null;
      }     
        if((regM instanceof Reg_Maestros))
       {
          regM.dispose();
          regM=null;
       }
        
        if(!(regH instanceof Reg_Horarios))
       {
           try
           {
              regH =new Reg_Horarios();
              CenterJInternalFrame(regH);
           }catch(Exception e)
           {
             JOptionPane.showMessageDialog(null,e.getMessage());
           }
      
       }
        
    }//GEN-LAST:event_btnhorarioActionPerformed

    private void btnaulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaulaActionPerformed
        // TODO add your handling code here:
        if((regCC instanceof Reg_Ciclo_Escolar))
      { 
          regCC.dispose();
          regCC= null;
      }      
        if((reg_MA instanceof Reg_Materias))
      { 
          reg_MA.dispose();
          reg_MA= null;
      }
        if((regE instanceof Reg_Equipos))
      { 
          regE.dispose();
          regE= null;
      }
        if((regU instanceof Reg_usuarios))
      { 
         regU.dispose();
         regU= null;
      }
           
        if((regM instanceof Reg_Maestros))
       {
          regM.dispose();
          regM=null;
       }
        
          if((regH instanceof Reg_Horarios))
      { 
          regH.dispose();
          regH= null;
      }
          
           if((RegCA instanceof Reg_Carreras))
      { 
          RegCA.dispose();
          RegCA= null;
      }
        if(!(regA instanceof Reg_Aulas))
       {
            try {
                regA =new Reg_Aulas();
                CenterJInternalFrame(regA);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
        
       }
    }//GEN-LAST:event_btnaulaActionPerformed

    private void btnCiclo_EscolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiclo_EscolarActionPerformed
        // TODO add your handling code here:
          if((regE instanceof Reg_Equipos))
      { 
          regE.dispose();
          regE= null;
      }
        if((reg_MA instanceof Reg_Materias))
      { 
          reg_MA.dispose();
          reg_MA= null;
      }          
        if((regU instanceof Reg_usuarios))
      { 
         regU.dispose();
         regU= null;
      }
           
        if((regM instanceof Reg_Maestros))
       {
          regM.dispose();
          regM=null;
       }
         if((RegCA instanceof Reg_Carreras))
      { 
          RegCA.dispose();
          RegCA= null;
      }
          if((regH instanceof Reg_Horarios))
      { 
          regH.dispose();
          regH= null;
      }
          
        if((regA instanceof Reg_Aulas))
       {
          regA.dispose();
           regA=null;
       }
          if(!(regCC instanceof Reg_Ciclo_Escolar))
       {
              try {
                  regCC =new Reg_Ciclo_Escolar();
                  CenterJInternalFrame(regCC);
              } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, ex.getMessage());
              }
        
       }
    }//GEN-LAST:event_btnCiclo_EscolarActionPerformed

    private void btnCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrerasActionPerformed
        // TODO add your handling code here:
             if((regE instanceof Reg_Equipos))
      { 
          regE.dispose();
          regE= null;
      }
        if((reg_MA instanceof Reg_Materias))
      { 
          reg_MA.dispose();
          reg_MA= null;
      }                       
        if((regU instanceof Reg_usuarios))
      { 
         regU.dispose();
         regU= null;
      }
           
        if((regM instanceof Reg_Maestros))
       {
          regM.dispose();
          regM=null;
       }
        
          if((regH instanceof Reg_Horarios))
      { 
          regH.dispose();
          regH= null;
      }
          
        if((regA instanceof Reg_Aulas))
       {
          regA.dispose();
           regA=null;
       }
          if((regCC instanceof Reg_Ciclo_Escolar))
       {
              
                  regCC.dispose();
                  regCC=null;
       }
            if(!(RegCA instanceof Reg_Carreras))
       {
              try {
                  RegCA =new Reg_Carreras();
                  CenterJInternalFrame(RegCA);
              } catch (Exception ex) {
              JOptionPane.showMessageDialog(null,ex.getMessage());
              }         
       }
     
    }//GEN-LAST:event_btnCarrerasActionPerformed

    private void btnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriasActionPerformed
              if((regE instanceof Reg_Equipos))
      { 
          regE.dispose();
          regE= null;
      }
        if((RegCA instanceof Reg_Carreras))
      { 
          RegCA.dispose();
          RegCA= null;
      }                       
        if((regU instanceof Reg_usuarios))
      { 
         regU.dispose();
         regU= null;
      }
           
        if((regM instanceof Reg_Maestros))
       {
          regM.dispose();
          regM=null;
       }
        
          if((regH instanceof Reg_Horarios))
      { 
          regH.dispose();
          regH= null;
      }
          
        if((regA instanceof Reg_Aulas))
       {
          regA.dispose();
           regA=null;
       }
          if((regCC instanceof Reg_Ciclo_Escolar))
       {
              
                  regCC.dispose();
                  regCC=null;
       }
          
         if((RegCA instanceof Reg_Carreras))
       {       
           RegCA.dispose();
           RegCA=null;      
       }   
            if(!(reg_MA instanceof Reg_Materias))
       {
           try {
              reg_MA =new Reg_Materias();
              CenterJInternalFrame(reg_MA);
              } catch (Exception ex) {
              JOptionPane.showMessageDialog(null,ex.getMessage());
              }         
       }
            
       
    }//GEN-LAST:event_btnMateriasActionPerformed

 public void CenterJInternalFrame(JInternalFrame internalframe)
    {
        
        int x=(jplRegescritorio.getWidth()/2)-internalframe.getWidth()/2;
        int y=(jplRegescritorio.getHeight()/2)-internalframe.getHeight()/2;
        if(internalframe.isShowing())
        {
          internalframe.setLocation(x, y);
        }
        else
        {
            jplRegescritorio.add(internalframe);
            internalframe.setLocation(x, y);
            internalframe.show();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarreras;
    private javax.swing.JButton btnCiclo_Escolar;
    private javax.swing.JButton btnMaterias;
    private javax.swing.JButton btnaula;
    private javax.swing.JButton btnequipo;
    private javax.swing.JButton btnhorario;
    private javax.swing.JButton btnmaestros;
    private javax.swing.JButton btnusuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jplRegescritorio;
    // End of variables declaration//GEN-END:variables
}
